### ISSUE TITLE
`tf-state` File is One Per Repo

### ISSUE THREAD

**Issue by DavidNic11** [bitovi/github-actions-deploy-static-site-to-aws#10]
Hello!

I'm working on deploying a couple applications from a package-based Nx mono-repo and I'm running into an issue with terraform.

I have a single job that runs an nx build and uploads the different project builds to different artifacts. from there multiple jobs at once pull their respective artifacts and try to s3 deploy. The action file is pretty long but here's a small snippet of it. 

```yml
name: Deploy
on:
  push:
    branches: [main]

jobs:
  create-builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: |
          npm i -g nx
          npm ci

      - name: Build
        run: nx run-many -t build --parallel=10

      - name: Upload catalog build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: project-1-artifacts
          path: packages/project-1/dist

      - name: Upload marketing build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: project-2-artifacts
          path: packages/project-2/dist

deploy-project-1:
    runs-on: ubuntu-latest
    needs: [create-builds]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: project-1-artifacts
          path: packages/project-1/dist

      - name: Create deploy-bucket
        uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
          checkout: false
          aws_site_source_folder: packages/project-1/dist

          tf_action: "apply"
          tf_state_bucket_destroy: true

          aws_site_cdn_enabled: true

          aws_r53_domain_name: <URL>
          aws_r53_sub_domain_name: project-1
          aws_r53_create_sub_cert: true

          aws_site_bucket_name: project-1

  deploy-project-2:
    runs-on: ubuntu-latest
    needs: [create-builds]

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: project-2-artifacts
          path: packages/project-2/dist

      - name: Create deploy-bucket
        uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1
          checkout: false
          aws_site_source_folder: packages/project-2/dist

          tf_action: "apply"
          tf_state_bucket_destroy: true

          aws_site_cdn_enabled: true

          aws_r53_domain_name: <URL>
          aws_r53_sub_domain_name: project-2
          aws_r53_create_sub_cert: true

          aws_site_bucket_name: project-2


```

This is the error I'm receiving.

```
Creating TF_STATE_BUCKET: <repo-name>-tf-state
{
    "Location": "/<repo-name>-main-tf-state"
}
Access to bucket confirmed. Can create and delete a tf-state file
Creating provider.tf
In generate_provider.sh


Run echo "::group::Terraform Init"
Terraform Init
Run echo "::group::Terraform Validate"
Terraform Validate
Run echo "::group::Terraform Plan"
Terraform Plan
Run echo "::group::Terraform Apply"
Terraform Apply
Run echo "## Workflow failed to run :fire:" >> $GITHUB_STEP_SUMMARY
  echo "## Workflow failed to run :fire:" >> $GITHUB_STEP_SUMMARY
  echo "Please check the logs for possible errors." >> $GITHUB_STEP_SUMMARY
  echo "If you consider this is a bug in the Github Action, please submit an issue to our repo." >> $GITHUB_STEP_SUMMARY
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/92d1ace5-b320-49cd-8fa2-73fb7639d659
```

When using a single project it works. From what I've gathered the tf-state file is 1 per repo so the action has issues deploying multiple projects from the same repo.
